### ISSUE TITLE
Styling classes not applied

### ISSUE THREAD

**Issue by zeeshan09** [scriptcoded/sql-highlight#3]
The style classes are there on the span tags, but I don't see any associated styles being applied, which just makes the whole thing look like plain text.

**"Select [ProductKey] <span class=\"sql-hl-special\">,</span> [ProductAlternateKey] <span class=\"sql-hl-special\">,</span> [ProductSubcategoryKey] <span class=\"sql-hl-keyword\">FROM</span> [Sandbox].[Product_Test]"**

**Comment by scriptcoded** [comment]
This is the intended behavior. When outputting HTML no styling is assumed, and only classes are applied to the spans. This means that you can provide your own coloring using CSS.

Below is a CSS snippet for a simple color scheme. It also applies a monospace font and black backgrund to any `code`-tag with the `sql` class.

```css
code.sql {
  font-family: monospace;
  background-color: #000;
}

.sql-hl-keyword {
  color: #f000f0;
}
.sql-hl-function {
  color: #ff0000;
}
.sql-hl-number {
  color: #00ff00;
}
.sql-hl-string {
  color: #00ff00;
}
.sql-hl-special {
  color: #ffff00;
}
.sql-hl-bracket {
  color: #ffff00;
}
```

Then with the following HTML:
```html
<code class="sql">
  <span class="sql-hl-keyword">SELECT</span> <span class="sql-hl-string">`id`</span><span class="sql-hl-special">,</span> <span class="sql-hl-string">`username`</span> <span class="sql-hl-keyword">FROM</span> <span class="sql-hl-string">`users`</span> <span class="sql-hl-keyword">WHERE</span> <span class="sql-hl-string">`email`</span> <span class="sql-hl-special">=</span> <span class="sql-hl-string">'test@example.com'</span>
</code>
```

It will yield this output:

![Screenshot from 2019-09-27 16-14-33](https://user-images.githubusercontent.com/6452991/65776216-f4575a00-e141-11e9-85a7-847e640afa5b.png)
